### PR TITLE
Implementing clang static code analysis

### PR DESCRIPTION
**Pull request by G-Ragghianti**
## Pull Request Description
Implement clang static code analysis from LLVM "scan-build" utility.

## Author Checklist
- [x] **Description**
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test failures_, etc
- [x] **Commits**
_Commits_ are self contained and only do one thing
_Commits_ have a header of the form: `module: short description`
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its solution
- [ ] **Tests**
The PR needs to pass all the tests

### CODE REVIEW

**Comment by G-Ragghianti** [comment]
I'm currently waiting for the build of llvm to finish so that the action will have access to the clang-analyze tool.

**Comment by gcongiu** [comment]
@G-Ragghianti I am not sure about the clang static analysis tool. Looking at the Coverity static analysis output I can see a lot of useful information for different parts of the code. The clang static analysis tool only reports one error and that's it. Maybe it can be configured differently to output more information.

**Comment by G-Ragghianti** [comment]
It actually reports 5 bugs found, not one.  This is in the direct output from the run of the tool.  It also provides details in a zip file that is saved as an artifact.  I see this as complementary to the coverity scan.  This clang tool has to distinct advantages that I can see right away:

1. Clang's scan-build will return an error if bugs are found.  This is properly handled by github actions and can be used to prevent merging until the problems are resolved.  Then way coverity is running, it will only trigger the scan.  It won't return actionable results to github.
2. Clang's tool doesn't require login and management on a separate cloud service website. 

> @G-Ragghianti I am not sure about the clang static analysis tool. Looking at the Coverity static analysis output I can see a lot of useful information for different parts of the code. The clang static analysis tool only reports one error and that's it. Maybe it can be configured differently to output more information.

**Comment by gcongiu** [comment]
@G-Ragghianti ok I missed the ones in the middle. Ok I will look at the artefacts as well. I think this is fine. If it is rebased onto master already we can merge it.

> It actually reports 5 bugs found, not one. This is in the direct output from the run of the tool. It also provides details in a zip file that is saved as an artifact. I see this as complementary to the coverity scan. This clang tool has to distinct advantages that I can see right away:
> 
> 1. Clang's scan-build will return an error if bugs are found.  This is properly handled by github actions and can be used to prevent merging until the problems are resolved.  Then way coverity is running, it will only trigger the scan.  It won't return actionable results to github.
> 2. Clang's tool doesn't require login and management on a separate cloud service website.
> 
> > @G-Ragghianti I am not sure about the clang static analysis tool. Looking at the Coverity static analysis output I can see a lot of useful information for different parts of the code. The clang static analysis tool only reports one error and that's it. Maybe it can be configured differently to output more information.

**Review by gcongiu — APPROVED** [review]

**Comment by G-Ragghianti** [comment]
Yes, it is rebased.  Thanks.

**Pull request merged**
