### PR TITLE
Creating initial CI files

### PR DESCRIPTION
**Pull request by G-Ragghianti**

### CODE REVIEW

**Comment by G-Ragghianti** [comment]
@gcongiu @jagode 
This PR is for the implementation of the current papi component checks that we were doing on Jenkins.  Please have a look and we can discuss.

**Comment by gcongiu** [comment]
Will these tests run automatically for every PR that is created/updated? Or they can be triggered by the PR author?

**Comment by G-Ragghianti** [comment]
They run automatically when the PR is created and when any changes are checked into the branch for the PR.  The only exception is if the PR is created by an external person, we will have to first approve the changes (for security) before the actions will run.

**Comment by G-Ragghianti** [comment]
Since the cuda tests are running very slow with many errors (and I understand that fixes for this are incoming), I've disabled the "run_tests.py" for the cuda component. I also removed the pcp component test until we are able to provide an environment where this can be tested (requires the pcp daemon).  All remaining tests are now passing.

**Comment by gcongiu** [comment]
Let's wait for Heike to come back before merging

**Comment by gcongiu** [comment]
Gerald can you do a `git rebase master` and update this PR? I think we should merge this next.

**Comment by G-Ragghianti** [comment]
> @G-Ragghianti can you do a `git rebase master` and update this PR? I think we should merge this next.

I'm pretty sure that I did?

**Comment by gcongiu** [comment]
I am not sure what is going on with the history from this PR:
```
* 11b291fb2 libpfm4: update to commit 533633a
* df758148a buildsystem: fix install target in Makefile
* 641c1035c intel_gpu: fix test
* 5c6c0377c fort: do not compile fortran code if disabled
* f0b3fdf5c fort: add --disable-fortran switch
* 2e650df79 rocm_smi: fix bug in get_ntv_events_count
* 25ab60185 memory: fix bug in generic_get_memory_info
* 08480f49a sysdetect: fix rocm and rocm_smi dlopen logic
* 6a24e16be libpfm4: update to commit 52632c7
* 23dc56a68 cat: allow user to specify DCR/DCW sampling
* 3de2fbe91 cat: non-core events in multithreaded benchmarks
* c8b5f3d44 cat: refactor flops benchmark
* 62e00b3fa cat: addition of instructions benchmarks
* 924d42be8 SDE: Fix shutdown for a consistent global control struct
* b8860e9f1 Fix wrong dlsym for cuptiDisableKernelReplayMode
* f8e998e16 Removing pcp component test
* 4e436beb5 removing test of libmsr
* 9df7ee645 fixing lmsensors and rocm
* 242230f55 added ci support for libmsr and lm-sensors
* 1aa6346e8 Fixing component errors
* 2a9face7b Adding more components
* b28058e09 testing
* 35cc3a2aa testing
* a4aea7ae2 testing
* 2d7459bdd creating initial CI files
*   9dd16e490 Merged in jlinford/arm-neoverse (pull request #453)
|\
| * 05dc58024 Add minimal events for Arm Neoverse V2
| * e911f9511 Add minimal events for Arm Neoverse N2
| * 88e686f87 Add minimal events for Arm Neoverse V1
|/
*   756540df5 Merged in jlinford/neoverse-n1 (pull request #450)
|\
| * d4da29b07 Add minimal events for Arm Neoverse N1
|/
*   cf3ef8872 Merged in 2023.01.09_papi-701-release-prep (pull request #429)
```

What it should look like is:
```
* f82f1611d Removing pcp component test
* 212262012 removing test of libmsr
* c24c3efb9 fixing lmsensors and rocm
* 01aa6dc65 added ci support for libmsr and lm-sensors
* b678a3c63 Fixing component errors
* e61e3dcd3 Adding more components
* d7edf31cb testing
* 817221ef5 testing
* a2e2f2b2a testing
* 6a78b46a9 creating initial CI files
*   c366ba6a1 Merge pull request #11 from gcongiu/2023.05.26_arm-neoverse-v2-presets
|\
| * b969d25f2 Update Neoverse V2 events
|/
*   0869ef13a Merged in 2023.05.17_libpfm4-update (pull request #477)
|\
| * d87cb28dc libpfm4: update to commit 533633a
|/
*   3a3d09ae3 Merged in 2023.05.16_makefile-fort-fix (pull request #476)
```

Could you also squash the CI commits?

**Comment by G-Ragghianti** [comment]
I also don't know what is going on with the history, and I don't know how to fix it.  I did the git rebase that you suggested, and this was the result.

**Comment by G-Ragghianti** [comment]
Yes, I think you do.  Please feel free.

**Comment by gcongiu** [comment]
@G-Ragghianti please verify I haven't done anything wrong with your changes. I will approve and merge the PR afterwards. Thank you.

**Review by gcongiu — APPROVED** [review]

**Comment by G-Ragghianti** [comment]
Yes, the problem is that since I had initially created the CI scripts, we have updated the version of cuda that is provided.  I recommend that we change this to just "module load cuda".

**Pull request merged**
