### PR TITLE
Update libpfm4 to commit 4134cb

### PR DESCRIPTION
**Pull request by Treece-Burgess**
## Pull Request Description

[Update libpfm4](https://github.com/icl-utk-edu/papi/pull/224/commits/2299cc027987c576ac81617a6fb87e873a66fc9b)

Current with
commit 3abda5bc6c1af7f1b620dc594a806b3b5a4134cb
Author: Stephane Eranian <eranian@gmail.com>
Date:   Tue Aug 27 13:52:59 2024 -0700

    Optimize pfm_detect() for ARM processors

    Avoid calling pfmlib_getcpuinfo_attr() 3 times for each ARM PMU to
    detect. For a given processor, the function will always return the
    same information. Use the pfm_arm_cfg structure as a cache on
    subsequent calls.

    Note: this overall logic does not handle ARM hybrids right now.

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit b8b7d69e774c38618aa440f49d69814d109629f5
Author: Stephane Eranian <eranian@gmail.com>
Date:   Mon Aug 26 17:22:47 2024 -0700

    add L2D_CACHE and make L2D_CACHE_ACCESS alias for ARM Neoverse N1,N2,V2

    To match kernel and documentation. Patch provides an alias to avoid
    breaking existing scripts.

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit 0d216ee4082aef2d8cabfa9816cdb6d6560d1d3f
Author: Stephane Eranian <eranian@gmail.com>
Date:   Fri Aug 16 00:29:33 2024 -0700

    update Intel SapphireRapids core PMU to 1.24

    Updates the Intel SapphireRapids core PMU event table
    to latest Intel released version:

    Date   : 07/18/2024
    Version: 1.24"

    From gitub.com/Intel/perfmon

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit 874ed7cff57271c5d4e530650eadce76e3dcaa14
Author: jdeokkim <jdeokkim@protonmail.com>
Date:   Mon Jul 22 17:08:07 2024 +0900

    Fix typos in docs/man3/pfm_get_perf_event_encoding.3

commit ffbfc5970897de87471e7cba64737dc13e2369cf
Author: jdeokkim <jdeokkim@protonmail.com>
Date:   Mon Jul 22 16:59:06 2024 +0900

    Fix typos in docs/man3/pfm_get_os_event_encoding.3

Note: The PAPI team does not have access to a machine with ARM and ARM Neoverse to test building PAPI with updated libpfm4 changes.
Built PAPI successfully on a machine with an Intel Sapphire Rapids (Intel(R) Xeon(R) Gold 6430) CPU and output from papi_native_avail shows updated names and descriptions.

## Author Checklist
- [x] **Description**
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test failures_, etc
- [x] **Commits**
_Commits_ are self contained and only do one thing
_Commits_ have a header of the form: `module: short description`
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its solution
- [x] **Tests**
The PR needs to pass all the tests

### CODE REVIEW

**Review by jagode — APPROVED** [review]

**Comment by G-Ragghianti** [comment]
This was merged, but it is failing one of the tests...

**Comment by Treece-Burgess** [comment]
@G-Ragghianti It is failing the PAPI_SPACK GitHub action because of the Cuda Component failing due to Cuda version 12.6. Which I have been able to reproduce now on Leconte. I have created Issue #225 to track this. 

The failure doesn't stem from the changes in this commit.

**Comment by G-Ragghianti** [comment]
Yes I see that the failure is not directly caused by a code change in the repo, but it is more an effect of the changing external environment.  This is somewhat of a philosophical point, but I would encourage these problems to be fixed when discovered if the merge is not urgent.  Otherwise, the problem will be kicked down the road indefinitely, and the CI will start becoming less useful as an indicator.  In this case, we could fix CUDA at a known good version (12.5.1) in the CI until the compatibility with cuda@12.6 is implemented.

**Comment by Treece-Burgess** [comment]
@G-Ragghianti I understand and I agree. We had users asking for the latest libpfm4 commits to be merged into master, and due to me locally testing as well as the error stemming from the Cuda component I went ahead and merged. 

Just from what I looked into for the Cuda component issue, I do not believe it will be a quick fix. 

I think dropping the Cuda version to 12.5.1 for PAPI_SPACK makes sense and is a good idea for now.

**Pull request merged**
