### PR TITLE
Update Makefile - CUDA 12.2

### PR DESCRIPTION
**Pull request by ametere-ssi**
Adding these two extra options to compiler and linker will produce successful compilation for my machine with gcc 9.4.0 and CUDA 12.2. Compilation fails otherwise.

## Author Checklist
- [1] Alfredo Metere, Samsung Semiconductor, Inc.
This fix addresses compilation failure of CUDA module tests on GCC v.9.4.0 and CUDA 12.2.
- changed two lines in the Makefile of CUDA module test.
The PR needs to pass all the tests

### CODE REVIEW

**Comment by Treece-Burgess** [comment]
@ametere-ssi I have tested building the Cuda component with Cuda version 12.1 and GCC version 9.5.0. I run into the following error for the test files: 
```
/usr/bin/ld: HelloWorld.o:(.eh_frame+0xc7): undefined reference to `__gxx_personality_v0'
```
If I add `-lstdc++` to line 21 with `CUDALIBS` and build the Cuda component again with the same versions of Cuda and GCC mentioned above. I get a successful build with the utilities such as `papi_component_avail`, `papi_native_avail`, and `papi_command_line` working as expected. 

- Did you run into the same above error when building? If not can you post the error you ran into.
- What during compilation for you is requiring -pthread?

**Comment by ametere-ssi** [comment]
> @ametere-ssi I have tested building the Cuda component with Cuda version 12.1 and GCC version 9.5.0. I run into the following error for the test files:
> 
> ```
> /usr/bin/ld: HelloWorld.o:(.eh_frame+0xc7): undefined reference to `__gxx_personality_v0'
> ```
> 
> If I add `-lstdc++` to line 21 with `CUDALIBS` and build the Cuda component again with the same versions of Cuda and GCC mentioned above. I get a successful build with the utilities such as `papi_component_avail`, `papi_native_avail`, and `papi_command_line` working as expected.
> 
> * Did you run into the same above error when building? If not can you post the error you ran into.
> * What during compilation for you is requiring -pthread?

Yes, that is the error I was getting. Right after that, another one error showed up on concurrent_profiling:
"g++ -DPAPI_NUM_COMP=4 -g -DPAPI     -o concurrent_profiling concurrent_profiling.o ../../../testlib/libtestlib.a ../../../libpapi.a -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.2/lib64 -lcudart -lcuda -lstdc++ -ldl
/usr/bin/ld: concurrent_profiling.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status"

which I fixed by adding the -pthread option.

**Comment by Treece-Burgess** [comment]
@ametere-ssi I just double checked, and I am not seeing:
```
"g++ -DPAPI_NUM_COMP=4 -g -DPAPI -o concurrent_profiling concurrent_profiling.o ../../../testlib/libtestlib.a ../../../libpapi.a -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.2/lib64 -lcudart -lcuda -lstdc++ -ldl
/usr/bin/ld: concurrent_profiling.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status"
```
In my build output. What is the output you get when you run `ldd --version`?

**Comment by ametere-ssi** [comment]
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31

**Comment by jagode** [comment]
@ametere-ssi : I created PR https://github.com/icl-utk-edu/papi/pull/245 that fixes the issue of having to manually add libstdc++ during the linking step. Could you please verify that it works for you as well? Thanks!

**Pull request closed without merging**
