### PR TITLE
Renaming cupti_common.* to papi_cupti_common.* to fix building in Cuda >=12.4

### PR DESCRIPTION
**Pull request by Treece-Burgess**
## Pull Request Description
This PR addresses the issue of building PAPI with the Cuda component with Cuda versions >= 12.4. Please see Issue #192 for more details.

This was tested with both Cuda 12.1 and Cuda 12.4, with success.

### Output for `./papi_component_avail` for PAPI build with Cuda 12.4:
```
Available components and hardware information.
--------------------------------------------------------------------------------
PAPI version             : 7.1.0.0
Operating system         : Linux 6.1.81-1.el9.elrepo.x86_64
Vendor string and code   : GenuineIntel (1, 0x1)
Model string and code    : Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (79, 0x4f)
CPU revision             : 1.000000
CPUID                    : Family/Model/Stepping 6/79/1, 0x06/0x4f/0x01
CPU Max MHz              : 3600
CPU Min MHz              : 1200
Total cores              : 80
SMT threads per core     : 2
Cores per socket         : 20
Sockets                  : 2
Cores per NUMA region    : 40
NUMA regions             : 2
Running in a VM          : no
Number Hardware Counters : 10
Max Multiplex Counters   : 384
Fast counter read (rdpmc): yes
--------------------------------------------------------------------------------

Compiled-in components:
Name:   perf_event              Linux perf_event CPU counters
Name:   perf_event_uncore       Linux perf_event CPU uncore and northbridge
Name:   cuda                    CUDA profiling via NVIDIA CuPTI interfaces
Name:   sysdetect               System info detection component

Active components:
Name:   perf_event              Linux perf_event CPU counters
                                Native: 165, Preset: 60, Counters: 10
                                PMUs supported: ix86arch, perf, perf_raw, bdw_ep

Name:   perf_event_uncore       Linux perf_event CPU uncore and northbridge
                                Native: 1126, Preset: 0, Counters: 152
                                PMUs supported: rapl, bdx_unc_cbo0, bdx_unc_cbo1, bdx_unc_cbo2, bdx_unc_cbo3, bdx_unc_cbo4
                                                bdx_unc_cbo5, bdx_unc_cbo6, bdx_unc_cbo7, bdx_unc_cbo8, bdx_unc_cbo9
                                                bdx_unc_cbo10, bdx_unc_cbo11, bdx_unc_cbo12, bdx_unc_cbo13, bdx_unc_cbo14
                                                bdx_unc_cbo15, bdx_unc_cbo16, bdx_unc_cbo17, bdx_unc_cbo18, bdx_unc_cbo19
                                                bdx_unc_ha0, bdx_unc_ha1, bdx_unc_imc0, bdx_unc_imc1, bdx_unc_imc4, bdx_unc_imc5
                                                bdx_unc_pcu, bdx_unc_qpi0, bdx_unc_qpi1, bdx_unc_ubo, bdx_unc_r2pcie
                                                bdx_unc_r3qpi0, bdx_unc_r3qpi1, bdx_unc_sbo0, bdx_unc_sbo1, bdx_unc_sbo2
                                                bdx_unc_sbo3

Name:   cuda                    CUDA profiling via NVIDIA CuPTI interfaces
                                Native: 1137744, Preset: 0, Counters: 30

Name:   sysdetect               System info detection component
                                Native: 0, Preset: 0, Counters: 0


--------------------------------------------------------------------------------
```
### Output for `./papi_command_line` for PAPI build with Cuda 12.4:
```
[ICL:leconte bin]$ ./papi_command_line cuda:::dram__bytes.avg:device=0

This utility lets you add events from the command line interface to see if they work.

Successfully added: cuda:::dram__bytes.avg:device=0

cuda:::dram__bytes.avg:device=0 :       1832 

----------------------------------
```

## Author Checklist
- [x] **Description**
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test failures_, etc
- [x] **Commits**
_Commits_ are self contained and only do one thing
_Commits_ have a header of the form: `module: short description`
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its solution
- [x] **Tests**
The PR needs to pass all the tests

### CODE REVIEW

**Comment by Treece-Burgess** [comment]
@wcohen This PR addresses Issue #192 that you had opened. I have already tested with the PAPI rpm and modified `papi.spec` you initially sent through email with the changes in this PR. The result was a successful build. If you want to test it out as well please do and let me know if there is any issue.

**Comment by wcohen** [comment]
The patches in the branch definitely address the problem with the build of the cuda component.  I did notice an additional issue with the code in the src/components/cuda/tests during the build (both with cuda-12.4 and cuda-12.5).  With:


` PAPI_CUDA_ROOT=/usr/local/cuda-12.4 make 
`

See nvcc doesn't accept the rpath linker option:

```
+ for comp in perf_event perf_event_uncore appio cuda coretemp example infiniband lustre micpower mx net pcp rapl stealtime sysdetect
+ make -C components/cuda/tests
make[1]: Entering directory '/home/wcohen/papi/src/components/cuda/tests'
/bin/sh: line 1: nvcc: command not found
(standard_in) 1: syntax error
/usr/local/cuda-12.4/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/usr/include -I/usr/local/cuda-12.4/include -g -ccbin='gcc' -DPAPI     -c -o HelloWorld.o HelloWorld.cu
/usr/local/cuda-12.4/bin/nvcc -g -ccbin='gcc' -DPAPI     -o HelloWorld HelloWorld.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.4/lib64 -lcudart -lcuda -Wl,-rpath=/home/wcohen/papi/src/libpfm4/lib:/home/wcohen/papi/src,--enable-new-dtags 
nvcc fatal   : Unknown option '-Wl,-rpath=/home/wcohen/papi/src/libpfm4/lib:/home/wcohen/papi/src,--enable-new-dtags'
make[1]: *** [Makefile:71: HelloWorld] Error 1
make[1]: Leaving directory '/home/wcohen/papi/src/components/cuda/tests'
make: *** [Makefile.inc:265: comp_tests] Error 2
```

**Comment by Treece-Burgess** [comment]
@wcohen I do not get the exact same error as yourself when I build, I get the following:
```
+ make -C components/cuda/tests
make[2]: Entering directory '/home/tburgess/papi_clean_installs/papi_leconte_clean_v3/papi/src/components/cuda/tests'
/bin/sh: line 1: bc: command not found
```
However, this was also present in Cuda 12.1 with the current code in the PAPI master branch. I will discuss with Heike and Anthony if we want to make this issue a separate PR later today.

**Comment by jagode** [comment]
@wcohen: Where is your nvcc located? Can you run "which nvcc"?

**Comment by wcohen** [comment]
I haven't set the path to include /usr/local/cuda-12.4/bin/. I assumed that the PAPI_CUDA_ROOT=/usr/local/cuda-12.4 would set the appropriate nvcc to use.  It looks like in the output that it finding /usr/local/cuda-12.4/bin/nvcc.  The problem is that nvcc doesn't understand the linker option.  Just tried with cuda-12.5:

```
$ export PATH=$PATH:/usr/local/cuda-12.5/bin
$ which nvcc
/usr/local/cuda-12.5/bin/nvcc
$ PAPI_CUDA_ROOT=/usr/local/cuda-12.5 make 
...
make[1]: Entering directory '/home/wcohen/papi/src/components/cuda/tests'
/usr/local/cuda-12.5/bin/nvcc -arch=native -g -ccbin='gcc' -DPAPI     -o HelloWorld HelloWorld.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-rpath=/home/wcohen/papi/src/libpfm4/lib:/home/wcohen/papi/src,--enable-new-dtags 
nvcc fatal   : Unknown option '-Wl,-rpath=/home/wcohen/papi/src/libpfm4/lib:/home/wcohen/papi/src,--enable-new-dtags'
make[1]: *** [Makefile:72: HelloWorld] Error 1
make[1]: Leaving directory '/home/wcohen/papi/src/components/cuda/tests'
make: *** [Makefile.inc:265: comp_tests] Error 2
```

It looks like the question is where is the '-Wl,-rpath=...' coming from.  See it in the configure.in for LDFLAGS and it ends up in the configure file.  These are the stock files and don't have any local changes.

For the problem with bc. It looks like the machine that the builds are being done on do not have bc installed and bc is used in the following part of the Makefile:

```
NVCC_VERSION := $(shell nvcc --version | grep -oP '(?<=release )\d+\.\d+')
ifeq ($(shell echo "$(NVCC_VERSION) >= 11.6" | bc), 1)
    NVCFLAGS := -arch=native
else
    NVCFLAGS :=
endif
```

**Comment by jagode** [comment]
> It looks like the question is where is the '-Wl,-rpath=...' coming from. See it in the configure.in for LDFLAGS and it ends up in the configure file. These are the stock files and don't have any local changes.

If you set `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:path-to-papi-lib`  then this should overwrite the LDFLAGS settings from the configure. Could you try this, please?

**Comment by wcohen** [comment]
It appears that -Xlinker should be used rather than -Wl to pass options to the linker according to:

https://github.com/mesonbuild/meson/issues/11234

Need some other tweaks to nvcc to link with the appropriate files.  As tried adding a quick and dirty NVLDFLAGS below to the papi/components/cuda/tests/Makefile and change the LDFLAGS with NVCC to NVLDFLAGS:
`
NVLDFLAGS =  -Xlinker -rpath=/home/wcohen/papi/src/libpfm4/lib:/home/wcohen/papi/src,--enable-new-dtags 
`
Resulted in different error:

```
+ make -C components/cuda/tests
make[1]: Entering directory '/home/wcohen/papi/src/components/cuda/tests'
/usr/local/cuda-12.5/bin/nvcc -arch=native -g -ccbin='gcc' -DPAPI     -o HelloWorld HelloWorld.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Xlinker -rpath=/home/wcohen/papi/src/libpfm4/lib:/home/wcohen/papi/src,--enable-new-dtags 
nvcc warning : Cannot find valid GPU for '-arch=native', default arch is used
nvcc fatal   : Don't know what to do with '../../../libpapi.so.7.1.0.0'
make[1]: *** [Makefile:73: HelloWorld] Error 1
make[1]: Leaving directory '/home/wcohen/papi/src/components/cuda/tests'
make: *** [Makefile.inc:265: comp_tests] Error 2
```
Might be a good idea to look at the [cuda samples](https://github.com/NVIDIA/cuda-samples) to see how the samples link in native libraries into cuda code.

**Comment by jagode** [comment]
@wcohen: Initially, I wasn't able to reproduce your problem. However, after some digging, I saw that you are linking tests with PAPI's shared library, while I was using the static one. After reconfiguring PAPI with `--with-shlib-tools`, I was able to reproduce the issue.

I suggest the following solution, which resolved the issue for me. Instead of linking with `nvcc`, we can use the chosen C compiler.

In the cuda/tests Makefile, replace `$(NVCC) $(NVCFLAGS)` with `$(CC) $(CFLAGS)` in the linker lines for all tests, and add `CFLAGS += -g $(PAPI_FLAG)` at the top of the Makefile.

With this modification, I was able to successfully compile the CUDA tests when linked with the shared PAPI library.

Here is how the compilation and linking look for one of the CUDA tests:

```
/apps/spacks/2023-11-15/opt/spack/linux-rocky9-x86_64/gcc-11.3.1/cuda-12.1.1-sy7jsrftb4zgl6cy5m3hq3t2vucgtywa/bin/nvcc -I. -I../../.. -I../../../testlib -I../../../validation_tests -I/home/jagode/02_Toolz/papi/src/install/include -I/apps/spacks/2023-11-15/opt/spack/linux-rocky9-x86_64/gcc-11.3.1/cuda-12.1.1-sy7jsrftb4zgl6cy5m3hq3t2vucgtywa/include -g -ccbin='gcc' -DPAPI     -c -o HelloWorld.o HelloWorld.cu
gcc -DHAVE_CUDA -DHAVE_NVML -DPAPI_NUM_COMP=4 -g -DPAPI     -o HelloWorld HelloWorld.o ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/apps/spacks/2023-11-15/opt/spack/linux-rocky9-x86_64/gcc-11.3.1/cuda-12.1.1-sy7jsrftb4zgl6cy5m3hq3t2vucgtywa/lib64 -lcudart -lcuda -Wl,-rpath=/home/jagode/02_Toolz/papi/src/libpfm4/lib:/home/jagode/02_Toolz/papi/src,--enable-new-dtags
```

**Comment by wcohen** [comment]
Yes, I should have included the configure I was using to build papi locally:

` ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-perf-events --with-pfm-incdir=/usr/include --with-pfm-libdir=/usr/lib64 --with-static-lib=no --with-shared-lib=yes --with-shlib-tools --with-components="appio cuda coretemp example infiniband lmsensors lustre micpower mx net pcp rapl stealtime"
`

I had the attached patch [cuda_test_make.txt](https://github.com/user-attachments/files/16313030/cuda_test_make.txt) and several of the cuda est files were made: HelloWorld, pthreads, and simpleMultiGPU.  However, it looks like nvcc is using some c++ code and build fails with:
```
+ make -C components/cuda/tests
make[1]: Entering directory '/home/wcohen/papi/src/components/cuda/tests'
/bin/sh: line 1: nvcc: command not found
(standard_in) 1: syntax error
gcc -DPAPI_NUM_COMP=16 -g -DPAPI     -o cudaOpenMP cudaOpenMP.o -lgomp ../../../testlib/libtestlib.a ../../../libpapi.so.7.1.0.0 -L../../../libpfm4/lib -lpfm -L/usr/local/cuda-12.5/lib64 -lcudart -lcuda -Wl,-rpath=/home/wcohen/papi/src/libpfm4/lib:/home/wcohen/papi/src,--enable-new-dtags 
/usr/bin/ld: cudaOpenMP.o:(.eh_frame+0x227): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:55: cudaOpenMP] Error 1
make[1]: Leaving directory '/home/wcohen/papi/src/components/cuda/tests'
make: *** [Makefile.inc:265: comp_tests] Error 2
```

Replaced the `$(CC) `with `$(CXX)` and the build is happy ([cuda_test_make_cxx.txt](https://github.com/user-attachments/files/16313432/cuda_test_make_cxx.txt) ).

**Comment by jagode** [comment]
> I had the attached patch [cuda_test_make.txt](https://github.com/user-attachments/files/16313030/cuda_test_make.txt) and several of the cuda est files were made: HelloWorld, pthreads, and simpleMultiGPU. However, it looks like nvcc is using some c++ code and build fails with...


@wcohen: Since the cuda/tests/Makefile specifies `-ccbin='$(CC)'`, the `nvcc` compiler will choose `$(CC)` as the host compiler. Hence, linking with `$(CXX)` should only be necessary if the test code uses C++, which is the case for `concurrent_profiling.cu` and `concurrent_profiling_noCuCtx.cu`. 

The other problems with `cudaOpenMP.cu` and `cudaOpenMP_noCuCtx.cu` can be resolved by separating compilation and linking.

See `git diff Makefile` here: 
[cuda_tests_Makefile_diff.txt](https://github.com/user-attachments/files/16316965/cuda_tests_Makefile_diff.txt)

Please let me know if the following Makefile works for you as well:
[Makefile.txt](https://github.com/user-attachments/files/16316984/Makefile.txt)

Note, github didn't allow me to attach the Makefile as is, so I added .txt. Running `mv Makefile.txt Makefile` before using it will be needed. 

Thank you!

**Comment by wcohen** [comment]
The suggested Makefile works for me. The `PAPI_CUDA_ROOT=/usr/local/cuda-12.5 make` completes without error on this branch.

**Review by jagode — APPROVED** [review]

**Pull request merged**
