### PR TITLE
Cuda Component Refactor to Add Device Qualifier

### PR DESCRIPTION
**Pull request by Treece-Burgess**
## Pull Request Description
This pull request addresses adding a device qualifier to the Cuda component. This refactor is similar to the ROCm refactor which added an instance and device qualifier (PR #123).

### Sample Output for `./papi_component_avail`
```
Name:   cuda                    CUDA profiling via NVIDIA CuPTI interfaces
                                Native: 141834, Preset: 0, Counters: 30
```

### Sample Output for `./papi_native_avail`
```
===============================================================================
| cuda:::dram__bytes.avg                                                       |      
|            # of bytes accessed in DRAM. Units=(bytes) Numpass=1              |      
|     :device=0                                                                |      
|            Mandatory device qualifier [0,1,2,3,4,5,6,7]                      |      
--------------------------------------------------------------------------------
```

Note: As of Cuda Version 12.6, the MetricsContext API has been removed and replaced with the MetricsEvaluator API. Due to this change, the Cuda component will only work with Cuda versions < 12.6. The PAPI team will be working to support both the MetricsContext API and MetricsEvaluator API. 

To prevent the above note from occurring a conditional has been placed inside `Rules.cuda`, where if a user uses a Cuda version >= 12.6, then the build will error out and a message will print. From my testing this will not interfere with `make clean`. Output can be seen below:
```
components/cuda/Rules.cuda:11: *** In Cuda 12.6, the MetricsContext API was replaced with the MetricsEvaluator API. Due to this, the Cuda component is currently being refactored to support Cuda versions >= 12.6.  Stop.
```

## Author Checklist
- [x] **Description**
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test failures_, etc
- [x] **Commits**
_Commits_ are self contained and only do one thing
_Commits_ have a header of the form: `module: short description`
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its solution
- [x] **Tests**
The PR needs to pass all the tests

### CODE REVIEW

**Comment by Treece-Burgess** [comment]
I am doing final cleanups/checks, but I will squash all the above commits into a single commit before merge. The merge commit message will have a note regarding the Cuda component not currently working with versions >= 12.6.

**Comment by Treece-Burgess** [comment]
As stands, I have tested with:

1. Personal scripts to start, stop, read, reset, cleanup, and more.
2. The following tests in the test directory: simpleMultipGPU, HelloWorld, and test_multi_read_and_reset.

From the above testing, no errors were encountered.

**Review by dbarry9 — APPROVED** [review]
I have tested these changes on the NVIDIA Hopper architecture using floating-point benchmarks. I monitored the correct event counts for half-, single-, and double-precision FMA operations on the device.

**Comment by jagode** [comment]
@Treece-Burgess : Since it has been approved by Daniel, please go ahead and merge it so the community can test it before the next release.

**Pull request merged**
